name: Daily BTC Predictor

on:
  schedule:
    - cron: "0 0 * * *"   # 8 AM PH time = 00:00 UTC
  workflow_dispatch:       # allow manual run

jobs:
  run-predictor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predictor
        run: python main.py

      - name: Commit and push results
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add prediction_log.csv
          git commit -m "Daily prediction update - $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
