name: Daily Bitcoin Prediction

on:
  schedule:
    - cron: "0 2 * * *"  # 10 AM PH time = 2 AM UTC
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install tensorflow scikit-learn pandas numpy requests yfinance
      - run: python main.py
