name: Daily BTC Predictor

on:
  schedule:
    - cron: "0 2 * * *"  # 02:00 UTC = 10:00 AM Philippines
  workflow_dispatch:

jobs:
  run-predictor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predictor
        run: python main.py

      - name: Commit results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add predictions.csv
          git commit -m "Update daily BTC predictions [skip ci]" || echo "No changes"
          git push
