name: Train Bitcoin Model

on:
  schedule:
    - cron: '0 2 * * *'  # 10 AM PH time (UTC+8)
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install tensorflow scikit-learn pandas numpy yfinance requests
      - run: python trainer.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Auto-trained Bitcoin model"
